POST http://localhost:5000/predict_sentiment
Content-Type: application/json

{
  "text": "hello"
}

GET http://localhost:5000


GET http://localhost:4000/user-details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZGF2aWQiLCJpYXQiOjE2OTYzNDMzMjcsImV4cCI6MTY5NjM0MzkyN30.UiznSqB1Q5suVuonqZTzm6HUGerASUtZwqI-2xb0Xck
###

POST http://127.0.0.1:5000/predict_sentiment
Content-Type: application/json

{
  "text": "I hate this shirt"
}

###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZGF2aWQiLCJpYXQiOjE2OTUxMDQ4MTgsImV4cCI6MTY5NTEwNTcxOH0.xXXn6wNyAolIwQhwuDkf-VJu2VkPA2xp6SvtEbH_xn0"}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"david@gmail.com",
    "password":"david123"
}