GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkRhdmlkQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2IiwiaWF0IjoxNjk1MDkxNDQ0LCJleHAiOjE2OTUwOTIwNDR9.4LBz2vOGmMQx6t7fQ2HC5URknW1NBuX1BYdKIlFXjgQ
###

POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGF2aWRfVEVTVCIsImlhdCI6MTY5NDk1NDYyNiwiZXhwIjoxNjk0OTU0NjQxfQ.Y2QdaF6kYzF16Bw0037TL33keGPDhx3W6uugP8_gZng"
}

###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZGF2aWQiLCJpYXQiOjE2OTUxMDQ4MTgsImV4cCI6MTY5NTEwNTcxOH0.xXXn6wNyAolIwQhwuDkf-VJu2VkPA2xp6SvtEbH_xn0"}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"david@gmail.com",
    "password":"david123"
}